// VerseData.swift — loads the bundled verse set and picks by calendar date.
// Self-contained: no network, no App Group. A curated, uplifting "verse of the day"
// set (verses.json, generated by scripts/gen_widget_verses.py); the day-of-year
// indexes into it, cycling if the set isn't a full 365.

import Foundation

struct Verse: Decodable, Hashable {
    let d: Int
    let full: String
    let short: String
    let ref: String
    /// "Eccl. 4:9". The Lock Screen falls back to this when the full reference
    /// and the days counter cannot share one line.
    let abbr: String
    /// Where the reader opens when the Lock Screen widget is tapped. Written by
    /// scripts/gen_widget_verses.py from the app's own book list, so `book` is
    /// always a name findBook() resolves.
    let book: String
    let chapter: Int
    let verse: Int?

    /// pamwe://bible/Ecclesiastes/4?verse=9 — an existing reader route, no new
    /// deep-link handling needed.
    var readerURL: URL? {
        var components = URLComponents()
        components.scheme = "pamwe"
        components.host = "bible"
        components.path = "/\(book)/\(chapter)"
        if let verse {
            components.queryItems = [URLQueryItem(name: "verse", value: String(verse))]
        }
        return components.url
    }
}

enum VerseStore {
    /// Decoded once from verses.json in the widget extension bundle.
    static let all: [Verse] = load()

    /// Shown if the bundle is somehow unreadable (also the widget placeholder).
    static let fallback = Verse(
        d: 0,
        full: "Though one may be overpowered, two can defend themselves. A cord of three strands is not quickly broken.",
        short: "A cord of three strands is not quickly broken.",
        ref: "Ecclesiastes 4:12",
        abbr: "Eccl. 4:12",
        book: "Ecclesiastes",
        chapter: 4,
        verse: 12
    )

    private static func load() -> [Verse] {
        guard
            let url = Bundle.main.url(forResource: "verses", withExtension: "json"),
            let data = try? Data(contentsOf: url),
            let verses = try? JSONDecoder().decode([Verse].self, from: data),
            !verses.isEmpty
        else { return [fallback] }
        return verses
    }

    /// day-of-year 1...366 -> verse, cycling if the set is shorter than the year.
    static func verse(forDayOfYear doy: Int) -> Verse {
        guard !all.isEmpty else { return fallback }
        let idx = (max(doy, 1) - 1) % all.count
        return all[idx]
    }

    static func verse(for date: Date, calendar: Calendar = .current) -> Verse {
        let doy = calendar.ordinality(of: .day, in: .year, for: date) ?? 1
        return verse(forDayOfYear: doy)
    }
}
