// VerseData.swift — loads the bundled verse set and picks by calendar date.
// Self-contained: no network, no App Group. A curated, uplifting "verse of the day"
// set (verses.json, generated by scripts/gen_widget_verses.py); the day-of-year
// indexes into it, cycling if the set isn't a full 365.

import Foundation

struct Verse: Decodable, Hashable {
    let d: Int
    let full: String
    let short: String
    let ref: String
}

enum VerseStore {
    /// Decoded once from verses.json in the widget extension bundle.
    static let all: [Verse] = load()

    /// Shown if the bundle is somehow unreadable (also the widget placeholder).
    static let fallback = Verse(
        d: 0,
        full: "Though one may be overpowered, two can defend themselves. A cord of three strands is not quickly broken.",
        short: "A cord of three strands is not quickly broken.",
        ref: "Ecclesiastes 4:12"
    )

    private static func load() -> [Verse] {
        guard
            let url = Bundle.main.url(forResource: "verses", withExtension: "json"),
            let data = try? Data(contentsOf: url),
            let verses = try? JSONDecoder().decode([Verse].self, from: data),
            !verses.isEmpty
        else { return [fallback] }
        return verses
    }

    /// day-of-year 1...366 -> verse, cycling if the set is shorter than the year.
    static func verse(forDayOfYear doy: Int) -> Verse {
        guard !all.isEmpty else { return fallback }
        let idx = (max(doy, 1) - 1) % all.count
        return all[idx]
    }

    static func verse(for date: Date, calendar: Calendar = .current) -> Verse {
        let doy = calendar.ordinality(of: .day, in: .year, for: date) ?? 1
        return verse(forDayOfYear: doy)
    }
}
