#!/usr/bin/env python3
"""
Turn the generated Bible catalogue into seed SQL.

Reads the run caches from gen_bible_catalogue.py (falling back to the gzipped
copies committed in scripts/, so this works long after the scratchpad is gone)
and writes supabase/seeds/bible_catalogue.sql: books, chapters, verses,
passages, vocabulary, in FK order, as batched upserts that are safe to re-run.

It refuses to emit a partial catalogue. 1,189 chapters and every chapter's
verse rows matching its n or nothing: a catalogue with holes would silently
shape retrieval, and nobody would know which holes were doing it.

    python3 scripts/emit_bible_catalogue_sql.py
"""
import gzip
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from bible_catalogue_spec import SPEC_VERSION, THEMES, TONES, GENRES, CAUTIONS  # noqa: E402
import gen_bible_catalogue as G  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "supabase" / "seeds" / "bible_catalogue.sql"
MODEL = "gpt-5.6-luna"
BATCH = 400


def load_cache(live, frozen):
    data = G.load(live)
    if data:
        return data
    with gzip.open(frozen, "rt") as f:
        return json.load(f)


def esc(s):
    return s.replace("'", "''")


def arr(items):
    # Vocabulary terms are [a-z-] only, so no per-element quoting is needed.
    return "'{" + ",".join(items) + "}'"


def batches(rows, insert_head, tail):
    out = []
    for i in range(0, len(rows), BATCH):
        out.append(insert_head + "\n" + ",\n".join(rows[i:i + BATCH]) + "\n" + tail)
    return out


def main():
    gens = load_cache(G.GEN_CACHE, ROOT / "scripts" / "bible_catalogue_cache.json.gz")
    texts = load_cache(G.TEXT_CACHE, ROOT / "scripts" / "bible_catalogue_text.json.gz")
    books = G.load(G.BOOKS_CACHE)
    if not books:
        books = json.loads((ROOT / "scripts" / "bible_catalogue_books.json").read_text())

    F = {k.split("|")[0]: v for k, v in gens.items()
         if k.split("|")[1] == SPEC_VERSION and k.split("|")[2] == MODEL}
    if len(F) != 1189:
        sys.exit(f"refusing to emit: {len(F)} chapters under spec {SPEC_VERSION} + {MODEL}, need 1189")

    b_rows, c_rows, v_rows, p_rows = [], [], [], []
    for name, meta in sorted(books.items(), key=lambda kv: kv[1]["order"]):
        b_rows.append(f"('{esc(name)}', '{meta['code']}', {meta['order']}, {meta['chapters']})")
        for ch in range(1, meta["chapters"] + 1):
            ref = f"{name} {ch}"
            rec, txt = F[ref], texts[ref]
            verse_text = {v["v"]: v["text"] for v in txt["verses"]}
            tagged = {v["v"]: v for v in rec["verses"]}
            if sorted(tagged) != sorted(verse_text) or len(tagged) != rec["_n"]:
                sys.exit(f"refusing to emit: {ref} verse rows disagree with its text")

            chd = rec["chapter"]
            c_rows.append(
                f"('{esc(name)}', {ch}, {rec['_n']}, '{esc(chd['summary'])}', "
                f"{arr(chd['themes'])}, '{chd['genre']}', '{chd['tone']}', '{SPEC_VERSION}')"
            )
            for v in rec["verses"]:
                v_rows.append(
                    f"('{esc(name)}', {ch}, {v['v']}, '{esc(verse_text[v['v']])}', "
                    f"{arr(v['themes'])}, '{v['tone']}', {arr(v['caution'])})"
                )
            for p in rec["passages"]:
                p_rows.append(
                    f"('{esc(name)}', {ch}, {p['start']}, {p['end']}, '{esc(p['summary'])}', "
                    f"{arr(p['themes'])}, '{p['tone']}', {arr(p['caution'])})"
                )

    voc_rows = (
        [f"('theme', '{t}', '{esc(g)}')" for t, g in THEMES.items()]
        + [f"('tone', '{t}', '')" for t in TONES]
        + [f"('genre', '{t}', '')" for t in GENRES]
        + [f"('caution', '{t}', '{esc(g)}')" for t, g in CAUTIONS.items()]
    )

    stmts = [
        "-- The Bible catalogue. Generated by scripts/emit_bible_catalogue_sql.py",
        f"-- from the {MODEL} run under spec {SPEC_VERSION}; do not hand-edit rows.",
        f"-- {len(c_rows)} chapters, {len(v_rows)} verses, {len(p_rows)} passages.",
        "",
    ]
    stmts += batches(
        b_rows,
        "insert into public.bible_books (book, code, ord, chapters) values",
        "on conflict (book) do update set code = excluded.code, ord = excluded.ord, chapters = excluded.chapters;",
    )
    stmts += batches(
        c_rows,
        "insert into public.bible_chapters (book, chapter, n_verses, summary, themes, genre, tone, catalogue_version) values",
        "on conflict (book, chapter) do update set n_verses = excluded.n_verses, summary = excluded.summary, "
        "themes = excluded.themes, genre = excluded.genre, tone = excluded.tone, catalogue_version = excluded.catalogue_version;",
    )
    stmts += batches(
        v_rows,
        "insert into public.bible_verses (book, chapter, verse, text, themes, tone, caution) values",
        "on conflict (book, chapter, verse) do update set text = excluded.text, themes = excluded.themes, "
        "tone = excluded.tone, caution = excluded.caution;",
    )
    stmts += batches(
        p_rows,
        "insert into public.bible_passages (book, chapter, verse_start, verse_end, summary, themes, tone, caution) values",
        "on conflict (book, chapter, verse_start) do update set verse_end = excluded.verse_end, summary = excluded.summary, "
        "themes = excluded.themes, tone = excluded.tone, caution = excluded.caution;",
    )
    stmts += batches(
        voc_rows,
        "insert into public.bible_vocabulary (kind, term, gloss) values",
        "on conflict (kind, term) do update set gloss = excluded.gloss;",
    )

    OUT.write_text("\n\n".join(stmts) + "\n")
    print(f"{len(b_rows)} books, {len(c_rows)} chapters, {len(v_rows)} verses, "
          f"{len(p_rows)} passages, {len(voc_rows)} vocabulary -> {OUT}")
    print(f"{OUT.stat().st_size / 1e6:.1f} MB")


if __name__ == "__main__":
    main()
