#!/usr/bin/env python3
"""
Generate the chapter-keyed reflection-prompt library (public.passage_prompts).

WHY THIS EXISTS
    Prompts used to live per plan and rotate. Ask Pamwe returned 2-3 prompts for
    a WHOLE plan and planBuilder dealt them round-robin (`prompts[i % len]`), so
    a 14-day Daniel plan had 3 prompts and day 5 ("Daniel 5") asked about the
    fiery furnace, which is Daniel 3. Curated plans rotated too: M'Cheyne had 30
    prompts for 365 days, John 7 for 21.

    Prompts are now keyed by CHAPTER and generated once, here. Any plan that
    includes Daniel 5 gets the Daniel 5 prompt, whether curated, hand-built, or
    generated by Ask Pamwe later. Generate once, store forever, never re-spend
    tokens on the same chapter, and both partners always see the same question.

WHAT IT DOES
    For each chapter: fetch the real WEB text from bible-api.com (the app's own
    source, so nothing is paraphrased or hand-typed), ask Claude for ONE
    couple-framed reflection question grounded in that chapter, and write the
    result as SQL for review.

    python3 scripts/gen_passage_prompts.py --sample      # ~20 varied chapters
    python3 scripts/gen_passage_prompts.py --plans       # every chapter used by
                                                         # the curated plans

    Fetches and generations are both cached to the scratchpad, so a re-run only
    costs tokens for chapters it has not done before.

MODEL / COST
    claude-haiku-4-5. A short generation per chapter: the whole Protestant canon
    (1,189 chapters) lands around $2-3 at standard rates, half that through the
    Batch API. Christian's call, 2026-07-26.

GUARDRAILS
    Pamwe points, never preaches. These are QUESTIONS grounded in what the
    chapter narrates, never an explanation of what it means and never doctrine.
    No em dashes: this is user-facing copy (CLAUDE.md).
"""
import argparse
import json
import os
import re
import sys
import time
import urllib.request
import urllib.parse
from pathlib import Path

try:
    import anthropic
except ImportError:
    sys.exit("pip install anthropic")

ROOT = Path(__file__).resolve().parent.parent
SCRATCH = Path(
    "/private/tmp/claude-501/-Users-christianmangwanda-Desktop-Pamwe/"
    "9c60bc58-1683-4ca9-a5cf-e5d69fb93672/scratchpad"
)
TEXT_CACHE = SCRATCH / "chapter_text_cache.json"
PROMPT_CACHE = SCRATCH / "passage_prompt_cache.json"
OUT_SQL = ROOT / "supabase" / "seeds" / "passage_prompts.sql"

MODEL = "claude-haiku-4-5"

# A spread across genres and testaments, so the voice can be judged on narrative,
# poetry, wisdom, law, gospel, and epistle rather than one register. Daniel 5 is
# deliberately included: it is the chapter where the mismatch was first noticed.
SAMPLE = [
    ("Genesis", 1), ("Genesis", 22), ("Exodus", 14), ("Ruth", 1),
    ("1 Samuel", 17), ("Psalms", 23), ("Psalms", 51), ("Proverbs", 3),
    ("Ecclesiastes", 3), ("Isaiah", 40), ("Daniel", 5), ("Daniel", 6),
    ("Hosea", 3), ("Matthew", 5), ("Mark", 4), ("Luke", 15),
    ("John", 11), ("Romans", 8), ("1 Corinthians", 13), ("Ephesians", 5),
]

SYSTEM = """You write a single reflection question for Pamwe, a devotional app where a Christian couple reads a chapter of the Bible together, then each writes a private reflection before revealing them to each other.

You are given the full text of one chapter. Write ONE question the two of them can answer about their own life after reading it.

Ground it in this chapter:
- Refer to what THIS chapter actually contains. Never reference a story, person, or image that is not in the text you were given.
- Anchor the question in something concrete from the chapter, so it could not be asked of any other passage.

Point, never preach. This is the app's governing rule:
- Do NOT explain what the passage means, teach its doctrine, or settle its interpretation.
- Do NOT tell them what to believe or what the "right" answer is.
- Ask about their life, their marriage, their week. The chapter is the doorway, not the lesson.

Voice:
- Second person plural, addressed to the couple: "you both", "each of you", "between you".
- Warm, plain, unhurried. Like a wise friend, not a study guide or a sermon.
- One or two sentences. Under 200 characters if you can.
- Never use em dashes. Use commas, colons, or periods.
- No preamble, no quotation marks around the question, no verse citation."""

USER_TEMPLATE = """Chapter: {ref}

{text}

Write the one reflection question for this chapter."""

SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "properties": {"prompt": {"type": "string"}},
    "required": ["prompt"],
}


def load(path):
    try:
        return json.loads(path.read_text())
    except Exception:
        return {}


def save(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=1, sort_keys=True))


def fetch_chapter(book, chapter, cache):
    """WEB text from bible-api.com, the same source src/lib/bible.ts uses."""
    key = f"{book} {chapter}"
    if key in cache:
        return cache[key]
    url = "https://bible-api.com/" + urllib.parse.quote(key) + "?translation=web"
    # bible-api.com 429s after roughly 15 rapid requests; pace and retry.
    for attempt in range(5):
        try:
            with urllib.request.urlopen(url, timeout=30) as r:
                data = json.loads(r.read().decode())
            text = re.sub(r"\s+", " ", data.get("text", "")).strip()
            if text:
                cache[key] = text
                save(TEXT_CACHE, cache)
                return text
        except Exception as e:
            print(f"    fetch {key} attempt {attempt + 1}: {e}", file=sys.stderr)
        time.sleep(3 * (attempt + 1))
    return None


def generate(client, book, chapter, text):
    ref = f"{book} {chapter}"
    # Long chapters (Psalm 119, 1 Kings 8) blow past what this needs; the opening
    # is plenty to ground a question and keeps every call cheap and uniform.
    body = text[:6000]
    msg = client.messages.create(
        model=MODEL,
        max_tokens=512,
        system=SYSTEM,
        output_config={"format": {"type": "json_schema", "schema": SCHEMA}},
        messages=[{"role": "user", "content": USER_TEMPLATE.format(ref=ref, text=body)}],
    )
    if msg.stop_reason == "refusal":
        print(f"    refused: {ref}", file=sys.stderr)
        return None
    raw = "".join(b.text for b in msg.content if b.type == "text")
    prompt = json.loads(raw)["prompt"].strip()
    # Belt and braces on the house rule: the model is told no em dashes, but this
    # is user-facing copy, so never let one through on the model's word alone.
    return prompt.replace(" — ", ", ").replace("—", ", ").replace(" – ", ", ")


def sql_escape(s):
    return s.replace("'", "''")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sample", action="store_true", help="the ~20 review chapters")
    ap.add_argument("--plans", action="store_true", help="every chapter in the curated plans")
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    if args.plans:
        chapters = json.loads((SCRATCH / "plan_chapters.json").read_text())
        chapters = [tuple(c) for c in chapters]
    else:
        chapters = SAMPLE

    key = os.environ.get("ANTHROPIC_API_KEY")
    if not key:
        env = ROOT / "supabase" / "functions" / ".env"
        for line in env.read_text().splitlines():
            if line.startswith("ANTHROPIC_API_KEY="):
                key = line.split("=", 1)[1].strip().strip('"').strip("'")
    if not key:
        sys.exit("ANTHROPIC_API_KEY not found")

    client = anthropic.Anthropic(api_key=key)
    texts = load(TEXT_CACHE)
    prompts = load(PROMPT_CACHE)

    for i, (book, chapter) in enumerate(chapters, 1):
        ref = f"{book} {chapter}"
        if ref in prompts:
            print(f"[{i}/{len(chapters)}] {ref} (cached)")
            continue
        print(f"[{i}/{len(chapters)}] {ref}")
        text = fetch_chapter(book, chapter, texts)
        if not text:
            print(f"    SKIPPED (no text)", file=sys.stderr)
            continue
        try:
            p = generate(client, book, chapter, text)
        except Exception as e:
            print(f"    generate failed: {e}", file=sys.stderr)
            continue
        if p:
            prompts[ref] = p
            save(PROMPT_CACHE, prompts)
        time.sleep(0.4)

    out = Path(args.out) if args.out else OUT_SQL
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "-- Chapter-keyed reflection prompts. Generated by",
        "-- scripts/gen_passage_prompts.py; see that file for the why.",
        "-- One question per chapter, grounded in that chapter's own text.",
        "",
    ]
    for ref in sorted(prompts):
        book, chapter = ref.rsplit(" ", 1)
        lines.append(
            "insert into public.passage_prompts (book, chapter, prompt) values "
            f"('{sql_escape(book)}', {chapter}, '{sql_escape(prompts[ref])}')\n"
            "  on conflict (book, chapter) do update set prompt = excluded.prompt;"
        )
    out.write_text("\n".join(lines) + "\n")
    print(f"\n{len(prompts)} prompts -> {out}")


if __name__ == "__main__":
    main()
